apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-bookstore
  labels:
    app: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore
  template:
    metadata:
      labels:
        app: bookstore
    spec:
      containers:
      - name: bookstore-container
        image: bookstore:1
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_URL
          value: "your_database_connection_string"
---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-service
spec:
  selector:
    app: bookstore-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort